# Generated by Django 3.2.6 on 2021-08-30 17:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='no email provided', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='no valid email', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='no valid phonenumber', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
